---
# Default variables for mac-system role

# Dock settings
dock_tilesize: 45

# System preferences
enable_save_panel_expanded: true
disable_smart_quotes: true
disable_smart_dashes: true
disable_autocorrect: true
show_all_extensions: true
enable_dark_mode: true
